#!/bin/bash
# Wake HK Aura Plus speaker via Bluetooth on Linux
# The speaker stays on WiFi in standby (ping works) but needs
# a BT A2DP connection + audio payload to fully wake up.
# After wake, TCP port 10025 becomes available for control.
#
# Configuration is loaded from wake_speaker.conf (generated by setup_wake_speaker.sh).
# If no config file exists, falls back to defaults below.
# Run setup_wake_speaker.sh first for guided setup!

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${WAKE_SPEAKER_CONF:-$SCRIPT_DIR/wake_speaker.conf}"

# Defaults (overridden by config file if present)
BT_MAC="XX:XX:XX:XX:XX:XX"
BT_NAME="HK Aura BT"
SPEAKER_IP="192.168.1.100"
SPEAKER_PORT=10025
MAX_WAIT=60
AUDIO_DURATION=5
INTRO_SONG_URL="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"

# Load config file if it exists
if [[ -f "$CONFIG_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$CONFIG_FILE"
else
    echo "[!] No config file found at $CONFIG_FILE"
    echo "[!] Using hardcoded defaults. Run setup_wake_speaker.sh for guided setup."
fi

log() { echo "[$(date +%H:%M:%S)] $1"; }

# Ensure XDG_RUNTIME_DIR is set (needed for headless/SSH sessions)
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
# Ensure D-Bus session bus is reachable (needed when invoked via SSH/non-login shell)
export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=/run/user/$(id -u)/bus}"

# Ensure PipeWire-Pulse is running (often inactive on headless systems)
if command -v systemctl &>/dev/null; then
    if ! systemctl --user is-active pipewire-pulse &>/dev/null; then
        log "Starting PipeWire-Pulse service..."
        systemctl --user start pipewire-pulse 2>/dev/null || true
        sleep 1
    fi
fi

# Ensure Bluetooth adapter is powered on
log "Powering on Bluetooth adapter..."
bluetoothctl power on > /dev/null 2>&1
sleep 1

# Check if already fully awake (TCP port open = awake, not just standby)
if timeout 3 bash -c "echo > /dev/tcp/$SPEAKER_IP/$SPEAKER_PORT" 2>/dev/null; then
    log "Speaker already awake (TCP port $SPEAKER_PORT open)"
    exit 0
fi

log "Speaker in standby - waking via Bluetooth + audio..."

# Connect via Bluetooth
log "Connecting to $BT_NAME ($BT_MAC)..."
CONNECT_OUTPUT=$(bluetoothctl connect "$BT_MAC" 2>&1)
echo "$CONNECT_OUTPUT"

if ! echo "$CONNECT_OUTPUT" | grep -q "Connection successful"; then
    log "First attempt failed, retrying in 3s..."
    sleep 3
    CONNECT_OUTPUT=$(bluetoothctl connect "$BT_MAC" 2>&1)
    echo "$CONNECT_OUTPUT"
    if ! echo "$CONNECT_OUTPUT" | grep -q "Connection successful"; then
        log "ERROR: Could not connect to speaker via Bluetooth"
        exit 1
    fi
fi

# Wait for A2DP sink to be registered
log "Waiting for audio sink..."
SINK_FOUND=false
for i in $(seq 1 15); do
    # Try pactl first, fall back to pw-cli
    if command -v pactl &>/dev/null && pactl list sinks short 2>/dev/null | grep -q "bluez_output"; then
        log "Bluetooth audio sink available (via pactl)"
        SINK_FOUND=true
        break
    elif command -v pw-cli &>/dev/null && pw-cli list-objects 2>/dev/null | grep -q "bluez_output"; then
        log "Bluetooth audio sink available (via pw-cli)"
        SINK_FOUND=true
        break
    fi
    sleep 1
done

if ! $SINK_FOUND; then
    log "WARNING: Could not detect audio sink, attempting playback anyway..."
fi

# Pin PulseAudio default sink to the BT speaker so mpv routes there explicitly.
# Without this, mpv may fall back to a dummy output when run via SSH.
BT_SINK=$(pactl list sinks short 2>/dev/null | grep -i "bluez_output" | awk '{print $2}' | head -1)
if [[ -n "$BT_SINK" ]]; then
    log "Setting default PulseAudio sink to: $BT_SINK"
    pactl set-default-sink "$BT_SINK"
else
    log "WARNING: No bluez_output sink found — audio may route to dummy output"
fi

# Send audio to fully wake the speaker
log "Playing audio for ${AUDIO_DURATION}s to wake speaker..."
if mpv --no-video --quiet --length="$AUDIO_DURATION" --ao=pulse "$INTRO_SONG_URL" 2>/dev/null; then
    log "Audio sent via PulseAudio"
elif mpv --no-video --quiet --length="$AUDIO_DURATION" --ao=pipewire "$INTRO_SONG_URL" 2>/dev/null; then
    log "Audio sent via PipeWire"
elif command -v pw-play &>/dev/null; then
    log "mpv audio failed, trying pw-play with silence..."
    timeout "$AUDIO_DURATION" pw-play /dev/zero --format=s16 --rate=44100 --channels=2 2>/dev/null || true
    log "Audio sent via pw-play"
else
    log "ERROR: All audio playback methods failed. Check PipeWire/PulseAudio installation."
fi

# Keep BT connected briefly to let speaker fully initialize
sleep 5

# Disconnect Bluetooth
log "Disconnecting Bluetooth..."
bluetoothctl disconnect "$BT_MAC" > /dev/null 2>&1

# Wait for TCP port to become available
log "Waiting for speaker TCP port $SPEAKER_PORT at $SPEAKER_IP..."
for i in $(seq 1 $MAX_WAIT); do
    if timeout 3 bash -c "echo > /dev/tcp/$SPEAKER_IP/$SPEAKER_PORT" 2>/dev/null; then
        log "Speaker fully awake! TCP port $SPEAKER_PORT open after ${i}s"
        exit 0
    fi
    sleep 1
done

log "TIMEOUT: Speaker TCP port did not open within ${MAX_WAIT}s"
exit 1